# Use postgres/example user/password credentials
version: "3.1"

services:

    i2b2app:
       build: ./i2b2app
       restart: on-failure
       environment:
         SECRETS: /run/secrets/secrets
       secrets:
         - secrets

    webserver:
        build: ./webserver
        restart:  on-failure
        ports:
           - 80:80
        environment:
          SECRETS: /run/secrets/secrets
        secrets:
          - secrets

    i2b2db:
        build: ./i2b2db
        restart:  on-failure
        ports:
          - 127.0.0.1:5432:5432
        environment:
          SECRETS: /run/secrets/secrets
        secrets:
          - secrets

    pgadmin:
        image: thajeztah/pgadmin4
        restart:  on-failure
        ports:
          - 127.0.0.1:5050:5050

secrets:
  secrets:
    file: secrets.txt
